### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by genguidanos** [blueherongis/Heron#50]
Is there anything similar that also is compatible with arm based SOC macs?

**Comment by blueherongis** [comment]
There is Heron for Mac available in the package manager, but, not having access to an ARM based Mac, I've only tested on an Intel based Mac.  Have you tried using it?

**Comment by philipbelesky** [comment]
I've been using it on an ARM mac. So far, no issues.

However, the version available in the packageManager when searching on an ARM Mac is `v0.3.8`, whereas on Windows I see the latest (`v0.4.1`). I'm not sure what your build process is like, but it is it possible that the [distribution tag](https://developer.rhino3d.com/guides/yak/the-anatomy-of-a-package/#distributions) got set to `win` rather than `any` at some point?

**Comment by blueherongis** [comment]
Unfortunately, the libraries for GDAL are not universal and need to be compiled for each architecture, so it's not a quick change to the distribution tag.  

For Heron `v.0.3.8`, I had grabbed osx-64 dylibs from someone's Unity repo (which I can't find anymore), but they aged quickly and I had focused development on the windows side.  However, I recently figured out how to build GDAL for osx-64 via Conda, so once again I have the most recent GDAL libraries to ship with Heron for Mac.  As a result, v0.4.2 is now available through Rhino's package manager with all the functionality of the latest windows version.  I'm hoping it works on ARM Macs, but if not, I can look into building the libraries for osx-Arm64.  Let me know what you find out.

**Comment by blueherongis** [comment]
Thanks for testing this.  It could be an error related to the target architecture for gdal.  A couple of things to check first:
1. Are you installing Heron from the package manager?
2. Can you post an example definition that throws this error so I can try to replicate it?

**Comment by philipbelesky** [comment]
Heron was installed from the package manger. Below should be a minimal reproduction example definition. The choice of SHP doesn't seem to affect whether the component throws, but I've included it for completeness.

[Heron Debug M1 Mac 2023-11-27.zip](https://github.com/blueherongis/Heron/files/13469025/Heron.Debug.M1.Mac.2023-11-27.zip)

**Comment by philipbelesky** [comment]
Heron was installed from the package manger. Below should be a minimal reproduction example definition. The choice of SHP doesn't seem to affect whether the component throws, but I've included it for completeness.

[Heron Debug M1 Mac 2023-11-27.zip](https://github.com/blueherongis/Heron/files/13469025/Heron.Debug.M1.Mac.2023-11-27.zip)

**Comment by philipbelesky** [comment]
Thanks for the test/update! Using that new GHA (copied into the Package Manager folder for Heron) I no longer see the error I described above, but I did see two new errors thrown:

> 1. The vector datasource was unreadable by this component. It may not a valid file type for this component or otherwise null/empty.
> 2. Solution exception:Object reference not set to an instance of an object

The file path provided to the component is the same as I've used successfully in earlier versions of Heron on a Mac so I'm relatively confident it's not an issue with the path itself or its parsing.

The area of code you mentioned is similar to what I've been looking at while trying to get Heron to build on MacOS Visual Studio. In particular, in `HeronConfiguration.cs` a number of methods off of `ConfigurationBuilder()` were throwing because they seemed to depend on some missing packages. I've fixed up those packages and been able to perform a macOS build of Heron over in [this branch](https://github.com/philipbelesky/Heron/commits/mac-build). With that build, the `Import Vector` component still throws, but now with:

> Solution exception:The type initializer for 'OSGeo.OGROgr' threw an exception.

Currently, attaching to Rhino isn't working on macOS builds, but I hope to address that and do some more useful debugging locally. In the meantime, would you like me to put through my `macos-builds` branch as a PR?

**Comment by blueherongis** [comment]
I think I've now found the reason `GdalConfiguration()` was exiting early.  I was telling it to look for a file path that does not exist at [line 90](https://github.com/blueherongis/Heron/blob/122588dc31280d6762ecae09c199bd8dc4341886/Heron/GdalConfiguration.cs#L90C1-L91C1), so the code would exit at line 108 before getting to set all the GDAL environment folder paths.  

>                     nativePath = Path.Combine(gdalPath, osxPlatform);

This means my previous fix in HeronComponent.cs is unnecessary.  Can you try the attached update to confirm this is true?

[Heron v0.4.2 update 2 for Mac.zip](https://github.com/blueherongis/Heron/files/13483663/Heron.v0.4.2.update.2.for.Mac.zip)


The idea with the `osxPlatform` subfolder to `gdalPath` was to emulate the windows approach which comes with the default `GdalConfiguration.cs` shipped with the GDAL Nuget package.  In this approach, there are `x86` and `x64` subfolders containing platform specific GDAL-related dlls which are created upon build and which are pointed to when `GdalConfiguration()` determines the correct architecture.  I was thinking of creating an osx-64 (or osx-arm64 if necessary) subfolder containing all the dylibs which are currently dumped into the Heron root folder to both keep the folder structure clean in Heron releases, but also make it easier to build for multiple architectures from one solution in Visual Studio.

Once I get this cleaner approach working on the [`cross-platform` branch](https://github.com/blueherongis/Heron/tree/cross-platform/), I can then look into pulling your `macos-builds` branch.

For reference, I'm building in Visual Studio (2019) for Mac and all GDAL dylibs are coming from a local conda folder on my machine.  I plan to commit these to the cross-platform branch if I can keep them structured as mentioned above.

**Comment by philipbelesky** [comment]
Thanks for clarifying that and for the providing the updated GHA. I can confirm that using that GHA, everything now seems to work as expected.

**Comment by blueherongis** [comment]
I've updated Heron to v0.4.2.1 with this fix on the package manager.
